name: environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - uncertainties
  - IPython
  - GSECARS lmfit
  - ipywidgets
  - plotly
  - seaborn
  - time
  - warnings
  - scipy
  - lmfit